apiVersion: actions.summerwind.dev/v1alpha1
kind: Runner
metadata:
  name: test-runner
  namespace: actions-runner-system
  labels:
    runner: test-runner
spec:
  repository: gihanb/test-app
  containerMode: kubernetes
  serviceAccountName: github-actions-sa
  workVolumeClaimTemplate:
    storageClassName: "hostpath"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
