apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default-runner-role
  namespace: actions-runner-system
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "secrets"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-role-binding
  namespace: actions-runner-system
subjects:
- kind: ServiceAccount
  name: default
  namespace: actions-runner-system
roleRef:
  kind: Role
  name: default-runner-role
  apiGroup: rbac.authorization.k8s.io